# Generated by Django 5.0 on 2024-03-23 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
            ],
        ),
    ]
