# Generated by Django 5.0 on 2024-03-23 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_registration_unitcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='unitCode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.unitcode'),
        ),
    ]
