# Generated by Django 5.0 on 2024-03-24 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_alter_registration_unitcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studentdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=20)),
                ('student_name', models.CharField(max_length=100)),
                ('programme', models.CharField(max_length=100)),
                ('national_id', models.CharField(max_length=20, null=True)),
                ('nationality', models.CharField(max_length=100, null=True)),
                ('religion', models.CharField(max_length=50, null=True)),
                ('DOB', models.DateField(max_length=100, null=True)),
                ('disability', models.CharField(max_length=100, null=True)),
                ('language', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
